name: Verification

# Run when manually triggered or on PRs with the 'run-verification' label
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Verification Check
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event.pull_request && contains(github.event.pull_request.labels.*.name, 'run-verification'))
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install verus toolchains
        run: ./scripts/vinstall.sh

      - name: Format spec/proof code
        run: |
          verusfmt --check `find ./ -name *.verus.rs` --verus-only

      - name: Verify svsm with verus
        run: cargo verify
        working-directory: kernel

      - name: Verify extra proof libs with verus
        run: cargo verify
        working-directory: verify_proof
